# Site settings
# Meta tags
title: Grantmakers.io
description: Quickly find data on 145,000 grantmaking institutions in the US. A free, open source project.

# Jekyll settings
baseurl: /profiles # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://www.grantmakers.io # Typically http://www.yourdomain.org
sass:
  sass_dir: assets/css/_sass
# The following helps troubleshoot automated build issues
strict_front_matter: true
liquid:
  error_mode: strict

portfolio_dir: v0
skip_related_projects: true
related_project_keys: []
related_min_common: 0.6
#Documentation for related_projects: https://github.com/codeinpink/jekyll-portfolio-generator

plugins_dir: _plugins

# Last updated - used in creating redirects if name has changed
# Format: "YYYY-MM-DDTHH:MM:SS.fffZ"
last_updated_grantmakers: '2024-01-06T04:07:48.353Z'
number_of_profiles: 145499

algolia_referral_link: https://www.algolia.com/?utm_source=grantmakersio&utm_medium=referral

# Algolia Public API Search Keys
algolia_public_key_grants: 96a419d65f67ff3b4c54939f8e90c220
algolia_public_key_profiles: ce4d584b0de36ca3f8b4727fdb83c658

# Donate links
donorbox_hosted_page_coffee: https://donorbox.org/buy-chad-a-coffee

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - _data/split_for_jekyll_json.js
  - _data/aggregated.json
  - split_for_markdown.js
  - pages
  - webpack
  - webpack.config.js
  - package.json
  - package-lock.json
