# Site settings
# Meta tags
title: Grantmakers.io
description: Quickly find data on 70,000 grantmaking institutions in the US. An open source project from your friends at SmarterGiving.

# Jekyll settings
baseurl: /profiles # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://www.grantmakers.io # Typically http://www.yourdomain.org
sass:
  sass_dir: assets/css/_sass

portfolio_dir: v0
skip_related_projects: true
related_project_keys: []
related_min_common: 0.6
#Documentation for related_projects: https://github.com/codeinpink/jekyll-portfolio-generator

plugins:
# - jekyll-sitemap

# Last updated - used in creating redirects if name has changed
# Format: "YYYY-MM-DD HH:MM:SS.fffZ"
last_updated_grantmakers: '2017-09-18 12:54:03.061Z'

algolia_referral_link: https://www.algolia.com/?utm_source=grantmakers_io

# Google Analytics
google-analytics: UA-84268197-1

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - _data/split_for_jekyll_json.js
  - split_for_markdown.js
