# A basic CircleCI config for a quick jekyll build to test out CircleCI
# Intended to be newbie friendly
#
# Globals required
# AGGREGATED_JSON_PUBLIC_URL
#
version: 2.1 # Set the CI version.
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.7.4-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem update --system
            gem install bundler
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-
            - gem-cache-v1-{{ arch }}-
      - run: bundle install --path=vendor/bundle && bundle clean
      - save_cache:
          paths:
            - vendor/bundle
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      # TODO Doesn't appear yarn import is working
      # Hence the need to yarn add the two packages
      - run: 
          name: Convert npm to yarn
          command: yarn import
      - run: yarn
      - run: yarn add stream-chain
      - run: yarn add stream-json
      - run: 
          name: Fetch aggregated.json
          command: wget $AGGREGATED_JSON_PUBLIC_URL -O _data/aggregated.json
      - run: 
          name: Split aggregated.json
          command: node _data/split-aggregated.js
      - run: 
          name: Build Jekyll
          command: JEKYLL_ENV=production bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'todo_change_to_source' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - circleci-project-setup