# A basic CircleCI config for a quick jekyll build to test out CircleCI
# Intended to be newbie friendly
#
# Globals required
# AGGREGATED_JSON_PUBLIC_URL
#
version: 2.1 # Set the CI version.
orbs:
  slack: circleci/slack@4.4.4
jobs:
  deploy:
    # If need to set a working_directory, set it here
    # Path will then be /home/circleci/project/[the new working_directory]
    # Not that useful in this test script as there's only one job (deploy)
    resource_class: small
    docker:
      - image: circleci/ruby:2.7.4-node
    steps:
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - circleci-project-setup